# Use root/bigdatainf as user/password credentials
version: '3.1'

services:

    # document-oriented database
    mongo:
      image: mongo:5.0.0
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      #volumes:
      #  - ./mongodb-data:/data/db
      networks:
        - gestbd_net

    mongo-express:
      image: mongo-express:latest
      restart: always
      ports:
        - 8081:8081
      depends_on:
        - mongo
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      networks:
        - gestbd_net


networks:
    gestbd_net:
      external: true

